artgris_maintenance:
    enable: false                # Activer/Désactiver la maintenance - par défaut: false
    ips: ["10.211.19.188"]    # IPs autorisées (prod) - par défaut: []
    response: 503                # Code HTTP de la page de maintenance - par défaut: 503
