doctrine:
    dbal:
        default_connection: 
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%' 
            customer:
                url: '%env(resolve:CUSTOMER_DATABASE_URL)%'
            security:
                url: '%env(resolve:SECURITY_DATABASE_URL)%'
                

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        controller_resolver:
            auto_mapping: true
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Acdb'
                        prefix: 'App\Entity'
                        alias: Main
            customer:
                connection: customer
                mappings:
                    Customer:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Acdb'
                        prefix: 'App\Entity\Acdb'
                        alias: customer
            security:
                connection: security
                mappings:
                    Security:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Security'
                        prefix: 'App\Entity\Security'
                        alias: Security
                        

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
