monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
  monolog:
    handlers:
      main:
        # un fichier est créé tout les jours pendant 10 jours puis supprime le plus ancien ( type: rotating_file &  max_files: 10 )
        type: fingers_crossed
        action_level: critical
        handler: nested
        excluded_http_codes: [404, 405]
        buffer_size: 50
        channels: ["!event"]
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!console"]
      nested:
        type: rotating_file
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: critical
        # channels: ["!event"]
        max_files: 30

when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: critical
        handler: nested
        excluded_http_codes: [404, 405]
        buffer_size: 50
        channels: ["!event"]
      symfony_mailer:
        type: symfony_mailer
        from_email: "developpement@arba.coop"
        to_email: "developpement@arba.coop"
        subject: "Environnement Prod | Une erreur critique est survenue : %%message%%"
        level: critical
        formatter: monolog.formatter.html
        content_type: text/html
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!console"]
      nested:
        type: rotating_file
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: critical
        max_files: 30

when@prod:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: critical
        handler: nested
        excluded_http_codes: [404, 405]
        buffer_size: 50
        channels: ["!event"]
      symfony_mailer:
        type: symfony_mailer
        from_email: "developpement@arba.coop"
        to_email: "developpement@arba.coop"
        subject: "Environnement Prod | Une erreur critique est survenue : %%message%%"
        level: critical
        formatter: monolog.formatter.html
        content_type: text/html
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!console"]
      nested:
        type: rotating_file
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: critical
        max_files: 30
