controllers_ArbaConnect:
    resource:
        path: ../src/ArbaConnect/Controller/
        namespace: App\ArbaConnect\Controller
    type: attribute

controllers_DeliveryDate:
    resource:
        path: ../src/DeliveryDateModule/Controller/
        namespace: App\DeliveryDateModule\Controller
    type: attribute
    
controllers_Inventory:
    resource:
        path: ../src/InventoryModule/Controller/
        namespace: App\InventoryModule\Controller
    type: attribute

request_password_reset:
    path: /forgotten-password
    controller: App\Controller\PasswordController::app_forgotten_password
    methods: [POST]

change_password:
    path: /change-password
    controller: App\Controller\PasswordController::app_change_password
    methods: [GET, POST]